### ISSUE TITLE
dREL syntax does not allow empty lists

### ISSUE THREAD

**Issue by merkys** [COMCIFS/dREL#1]
Current syntax does not allow empty lists, for example the following construction would be reported as error:
```
a = []
```
Is such behavior intended? [ddl.dic contains aforementioned constructions](https://github.com/COMCIFS/cif_core/blob/fe4e9861bb5d276373fe244e582860d51c1efbba/ddl.dic#L1378) and it would be great to know where the problem is.

**Comment by jamesrhester** [comment]
This is a mistake in the syntax, empty lists should certainly be allowed.

**Comment by jamesrhester** [comment]
Latest commit fixes this problem.

**Comment by vaitkus** [comment]
Are the fixes already reflected in the annotated grammar? I saw that the ``MISSING`` and ``NULL`` productions were added, however, these refer to the ``?`` and ``NULL`` strings appropriately. As such, the specific case mentioned by @merkys still does not seem to be supported.

**Comment by jamesrhester** [comment]
Sorry, forgot to commit the actual important changes! Should be there now.

**Comment by vaitkus** [comment]
Great, thank You.

**Comment by merkys** [comment]
Thanks for the prompt fix! Closing the bug.
