### ISSUE TITLE
Several potential missing builtins

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/dREL#13]
The `CIF_CORE` dictionary contains calls to the `AtoI`  and `Matrix` functions which do not seem to be defined in the `builtins.md` document. Are these functions indeed considered builtins?

**Comment by jamesrhester** [comment]
Yes, these are builtins and should be documented. As used in cif_core, `AtoI` obviously converts an Ascii character to an integer.

**Comment by vaitkus** [comment]
Does `AtoI` really only work with single characters or is it intended to handle multicharacter strings, e.g. "73"?

**Comment by jamesrhester** [comment]
See my comment on #14. Our only examples of use are with single characters.
