### ISSUE TITLE
dREL syntax does not allow function calls without assigments

### ISSUE THREAD

**Issue by merkys** [COMCIFS/dREL#2]
Current syntax does not allow function calls without assignments, for example the following construction would be reported as error:
```
a(b)
```
Is such behavior intended? [ddl.dic contains aforementioned constructions](https://github.com/COMCIFS/cif_core/blob/fe4e9861bb5d276373fe244e582860d51c1efbba/ddl.dic#L1382).

**Comment by jamesrhester** [comment]
The problem with allowing function calls to constitute statements by themselves is that grammar collisions are introduced that could be quite challenging to resolve. The one that came up immediately was deciding on whether a function call is an expression or a statement by itself. If the former, then an expression must be acceptable as a statement, but then other collisions are introduced (I am doing this checking using the Python Lark parser).

You are welcome to propose changes to the EBNF that would allow function calls to be resolved. The simpler solution is to change all such naked function calls to assignments.  I believe I have done this for all methods in cif_core.dic, but overlooked the code (that I wrote, whoops!) in ddl.dic.  

Can you see any issues with disallowing isolated function calls? It seems like a win for simplicity of implementation.

**Comment by vaitkus** [comment]
I just want to note that the ``_space_group.crystal_system`` data item definition from the ``cif_core`` still contains some isolated function calls in the form of Alert and Throw.

This issue is also mentioned in the ``annotated_grammar`` near the ``small_statement`` rule.

**Comment by merkys** [comment]
> The simpler solution is to change all such naked function calls to assignments.

This sounds fair. Moreover, this would give dREL feel of purely functional programming language, what is a nice feature by itself (IMO).

**Comment by merkys** [comment]
I am closing this issue as resolved. I have just opened COMCIFS/cif_core#132 to track the removal of isolated function calls from CIF_CORE.
